Threadsafety and Retry (#11)
* Fix undefined method 'merge' for RethinkDB::StreamTerm

* Fix undefined method 'values' for RethinkDB::DatumTerm

* Fix: Error: undefined method 'date' for RethinkDB::DatumTerm

* changes could be called without parameters or Hash or Namedtuple

* Add grant method for DBTerm

* Add index_drop to TableTerm

* use `Time.utc`, fix miscellaneous lints

* explicit arguments to improve documentation

* migrate to JSON::Serializable

* threadsafe connection with configurable retry

* cancellable cursors

`Cursor#stop` allows cleans up long-running connections like changefeeds

* refactor(connection): separate auth, message, cursor, and reorder module

* require "rethinkdb" and version bump

*v0.2.0*
- cancellable `RethinkDB::Cursor`
- migrate to `JSON::Serializable`
- refactor `RethinkDB::Connection`
- add `RethinkDB::DBTerm#grant` (Thanks Christian Kakesa)
- add `RethinkDB::DatumTerm#date` (Thanks Christian Kakesa)
- add `RethinkDB::DatumTerm#values` (Thanks Christian Kakesa)
- add `RethinkDB::StreamTerm#merge` (Thanks Christian Kakesa)
- add `RethinkDB::TableTerm#index_drop` (Thanks Christian Kakesa)

* add missing set operations for Datum

* add `delete` for `DatumTerm`

* add `count` and `slice` for RowsTerm

* normalize query options for `ChangefeedTerm#run`

Co-authored-by: Christian Kakesa <christian.kakesa@gmail.com>